apiVersion: apps/v1
kind: Deployment
metadata:
  name: "pi-sd-backend"
  labels:
    app: pi-sd
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
        - name: pi-sd-backend
          image: "riko07/pi-sd-backend:0.5.3-SNAPSHOT"
          imagePullPolicy: IfNotPresent
