apiVersion: v1
kind: Service
metadata:
  name: "pi-sd-backend-service"
  labels:
    app: pi-sd
spec:
  selector:
    tier: backend
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
